Rails:
 MeiserDeliveriesController:
  methods:
   print: 1
 CustomerDeliveriesController:
  methods:
   print: 1
   list: 0
 CashPayerDeliveriesController:
  methods:
   print: 1
   list: 1
 WeightingController:
  methods:
   print: 1